name: Metrics
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Botoaca-Florentina-Veronica
          filename: metrics.svg
          base: header
          plugin_isocalendar: yes
          plugin_people: yes
          plugin_people_limit: 0  # Afișează toți vizitatorii
          plugin_people_size: 28  # Dimensiunea avatarurilor
          plugin_people_types: visitors  # Doar vizitatori
